name: flutter_github_search
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  common_github_search:
    path: ../common_github_search
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true